version: '3.8'

services:

  springboot-microservice-jpa-cuscredit:
    build:
      context: ./springboot-microservice-jpa-cuscredit
    image: springboot-microservice-jpa-cuscredit-img
    container_name: springboot-microservice-jpa-cuscredit-api
    ports:
      - "8088:8080"
    networks:
      - mysqlnetwork

  springboot-microservice-jpa-billofmonth:
    build:
      context: ./springboot-microservice-jpa-billofmonth
    image: springboot-microservice-jpa-billofmonth-img
    container_name: springboot-microservice-jpa-billofmonth-api
    ports:
      - "8089:8080"
    networks:
      - mysqlnetwork

  springboot-microservice-jpa-billrecord:
    build:
      context: ./springboot-microservice-jpa-billrecord
    image: springboot-microservice-jpa-billrecord-img
    container_name: springboot-microservice-jpa-billrecord-api
    ports:
      - "8090:8080"
    networks:
      - mysqlnetwork

networks:
  mysqlnetwork:
    external: true  # 使用外部已存在的網路